resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: source
  type: git
  check_every: 24h
  source:
    uri: https://github.com/jonm/term2md

- name: pr
  type: pull-request
  check_every: 24h
  source:
    repository: jonm/term2md
    access_token: ((github-access-token))

jobs:
- name: build-pr
  plan:
  - get: pr
    trigger: true
    version: every
  - put: pr
    params:
      path: pr
      status: PENDING
  - task: pytest
    file: pr/ci/task_pytest.yml
    input_mapping: { source: pr }
    on_failure:
      put: pr
      params:
        path: pr
        status: FAILURE
  - put: pr
    params:
      path: pr
      status: SUCCESS
- name: build
  plan:
  - get: source
    trigger: true
    version: every
  - task: pytest
    image: jonm33/python3-ci
    file: source/ci/task_pytest.yml
