resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

- name: pypi
  type: docker-image
  source:
    repository: cfplatformeng/concourse-pypi-resource

resources:
- name: source
  type: git
  check_every: 24h
  source:
    uri: https://github.com/jonm/term2md

- name: pr
  type: pull-request
  check_every: 24h
  source:
    repository: jonm/term2md
    access_token: ((github-access-token))

- name: pypi
  type: pypi
  source:
    name: term2md
    packaging: any
    repository:
      username: ((pypi-username))
      password: ((pypi-password))

jobs:
- name: build-pr
  plan:
  - get: pr
    trigger: true
    version: every
  - put: pr
    params:
      path: pr
      status: PENDING
  - task: validate
    file: pr/ci/task_test_and_build.yml
    input_mapping: { source: pr }
    on_failure:
      put: pr
      params:
        path: pr
        status: FAILURE
  - put: pr
    params:
      path: pr
      status: SUCCESS
- name: build
  plan:
  - get: source
    trigger: true
    version: every
  - task: build
    file: source/ci/task_test_and_build.yml
  - put: pypi
    params:
      glob: 'dist/term2md-*.tar.gz'

